CREATE TABLE spells (
  id INTEGER PRIMARY KEY AUTOINCREMENT
  ,name TEXT NOT NULL
);

CREATE TABLE classes (
  id INTEGER PRIMARY KEY AUTOINCREMENT
  ,class TEXT NOT NULL
  ,spell INTEGER NOT NULL
  ,FOREIGN KEY(spell) REFERENCES spells(id)
)
